---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: false
configure_sudoers: true

configure_dock: false
dockitems_remove:
  - Maps
  - Reminders
  - TV
  - Music
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  - Photos
  - Contacts
  - Calendar
  - Notes
  - Mail
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist:
  - name: "Launchpad"
    path: "/System/Applications/Launchpad.app/"
    pos: 1
  - name: "App Store"
    path: "/System/Applications/App%20Store.app/"
    pos: 2
  - name: "Messages"
    path: "/System/Applications/Messages.app/"
    pos: 3
  - name: "FaceTime"
    path: "/System/Applications/FaceTime.app/"
    pos: 4
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 5
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 6
  - name: "Preview"
    path: "/System/Applications/Preview.app/"
    pos: 7
  - name: "GoodNotes"
    path: "/Applications/GoodNotes.app/"
    pos: 8
  - name: "Spark"
    path: "/Applications/Spark.app/"
    pos: 9
  - name: "System Preferences"
    path: "/System/Applications/System%20Preferences.app/"
    pos: 10
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 11
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 12
  - name: "Sublime Merge"
    path: "/Applications/Sublime Merge.app"
    pos: 13

# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

sudoers_custom_config: |
  %admin ALL=(ALL) NOPASSWD: ALL
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - curl
  - doxygen
  - duti
  - fd
  - fzf
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - iproute2mac
  - libevent
  - lua
  - sqlite
  - mcrypt
  - neovim
  - nmap
  - node
  - nvm
  - openjdk
  - php
  - ripgrep
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alacritty
  - alfred
  - amethyst
  - balenaetcher
  - bartender
  - brave-browser
  - clion
  - discord
  - docker
  - font-meslo-lg-nerd-font
  - hammerspoon
  - iina
  - intellij-idea
  - karabiner-elements
  - kicad
  - onyx
  - parallels
  - pycharm
  - sublime-merge
  - sublime-text
  - the-unarchiver
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
